# .streamlit/config.toml

[theme]
primaryColor = "#d32f2f"         # Navagis red for accents
backgroundColor = "#f4f4f4"      # Light modern gray background
secondaryBackgroundColor = "#ffffff" # Clean white for contrast
textColor = "#333333"            # Dark gray for better readability
font = "roboto"                  # Sleek, modern font

[general]
showWarningOnDirectExecution = false

