# .streamlit/config.toml
[theme]


primaryColor = "#d32f2f"         # Navagis red from the logo
backgroundColor = "#42a5f5"      # Blue background
secondaryBackgroundColor = "#f1f1f1" # Light gray for secondary sections
textColor = "#333333"            # Dark gray text for readability
font = "sans-serif"              # Clean, modern font

# Set general options
[general]
showWarningOnDirectExecution = false
